{
    'name': 'Chấm Công Việt Nam',
    'version': '18.0.1.0.0',
    'category': 'Human Resources/Attendance',
    'summary': 'Module chấm công tùy chỉnh cho doanh nghiệp Việt Nam',
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'hr_attendance',
        'hr_holidays',
        'web',
        'mail',
        'resource',
    ],
    'data': [
        'security/attendance_security.xml',
        'security/ir.model.access.csv',
        'data/attendance_holiday_data.xml',
        'data/attendance_overtime_data.xml',
        'data/attendance_rule_data.xml',
        'views/attendance_views.xml',
        'views/attendance_config_views.xml',
        'views/attendance_device_views.xml',
        'views/attendance_holiday_views.xml',
        'views/attendance_location_views.xml',
        'views/attendance_overtime_views.xml',
        'views/attendance_report_views.xml',
        'views/attendance_rule_views.xml',
        'views/attendance_shift_views.xml',
        'views/hr_employee_views.xml',
        'views/attendance_dashboard.xml',
        'views/attendance_menus.xml',
        'views/attendance_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vietnam_attendance/static/src/js/attendance_dashboard.js',
            'vietnam_attendance/static/src/js/attendance_mobile.js',
            'vietnam_attendance/static/src/js/attendance_qrcode.js',
            'vietnam_attendance/static/src/css/attendance_style.css',
        ],
        'web.assets_qweb': [
            'vietnam_attendance/static/src/xml/attendance_templates.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 105,
    'external_dependencies': {
        'python': ['qrcode', 'xlsxwriter'],
    },
    'images': ['static/description/icon.png'],
}